#150 How it works page created
mirrenil/arbetsmetodik pull request #151
Opened 2022-12-07 12:43 UTC by Erikisak

HowItWorks.tsx edited 
Styling and structure from figma-design
Instructions how to application works
Link to Sign Up added

Closes #150

2022-12-07 12:59 UTC, liinneea-a requested changes
Good work! Please change all tags containing text to `<Typography>` and format the while file to fix indentations

2022-12-07 12:59 UTC, liinneea-a commented on src/Pages/HowItWorks.tsx
> +        <Box sx={text1}>
All elements containing text should be in a `<Typography>` tag

2022-12-07 18:24 UTC, mirrenil submitted a review, later dismissed

2022-12-08 12:26 UTC, mirrenil approved these changes

2022-12-08 14:28 UTC, liinneea-a approved these changes

2022-12-08 14:28 UTC, merged