#74 Notification badge
mirrenil/arbetsmetodik pull request #183
Opened 2022-12-12 11:02 UTC by Erikisak

Notification badge added 
Badge will show in header when request i recieved
Closes #74

2022-12-12 11:04 UTC, mirrenil reviewed
Nice work! Can I assume that the badge disappears when a request has been answered?

2022-12-12 12:06 UTC, Erikisak commented
> Nice work! Can I assume that the badge disappears when a request has been answered?

Worked in Linneas branch so I also assumed that!

2022-12-12 13:02 UTC, mirrenil submitted a review, later dismissed

2022-12-12 13:11 UTC, liinneea-a requested changes
Nice!! Just add a key prop :)

2022-12-12 13:18 UTC, mirrenil commented on src/Components/Header.tsx
> +  const { myReceivedRequests, mySentRequests } = useUser();
is "mySentRequests" used somewhere?

2022-12-12 13:42 UTC, liinneea-a commented
A badge is now rendered as many times as user has requests. There should only be one badge (if user has requests)

2022-12-13 11:04 UTC, AdaHep approved these changes
Looks good :) mySentRequests on line  27 is still not used and can be removed 👍

2022-12-13 14:26 UTC, hazem-89 approved these changes

2022-12-13 14:26 UTC, mirrenil approved these changes
😮‍💨

2022-12-13 14:26 UTC, liinneea-a approved these changes

2022-12-13 14:28 UTC, merged